language: python

services:
 - docker
 
before_install:
 - docker build -t biologger/speciesprimer .
 - docker run -e TZ=Europe/Amsterdam -p 5000:5000 -p 9001:9001 biologger/speciesprimer /bin/sh -c "cd /home/pipeline/tests"
 - docker ps -a
 - docker run biologger/speciesprimer /bin/sh -c "cd /home/pipeline/tests; pip3 install codecov pytest pytest-cov"
 
# Run the unit test
script:
  - pytest --cov=speciesprimer

sudo: false
# Push the results back to codecov
after_success:
  - codecov
